import time
print("Let's start")
time.sleep(2)
print("Breath in and hold")
time.sleep(2)
print("1")
time.sleep(2)
print("2")
time.sleep(2)
print("3")
time.sleep(1.5)
print("Hold")
time.sleep(2)
print("4")
time.sleep(2)
print("5")
time.sleep(2)
print("Now exhale")
time.sleep(3)
print("Inhale")
time.sleep(2)
print("1")
time.sleep(2)
print("2")
time.sleep(2)
print("3")
time.sleep(1.5)
print("Hold")
time.sleep(2)
print("4")
time.sleep(2)
print("5")
time.sleep(2)
print("Now exhale")
time.sleep(3)
print("One more time")
time.sleep(2)
print("1")
time.sleep(2)
print("2")
time.sleep(2)
print("3")
time.sleep(1.5)
print("Hold")
time.sleep(2)
print("4")
time.sleep(2)
print("5")
time.sleep(2)
print("Exhale")
time.sleep(1.5)
print("Congratulations")